fix DF hashing bug (untested)
Should fix 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-1e594fb06987> in <module>
      1 dep_var = 'label'
      2 data_bunch = TabularDataBunch.from_df('data/', full_df, valid_df, dep_var, tfms=[FillMissing, Categorify],
----> 3                                       cat_names=[], cont_names=contin_vars, test_df=test_df)

/anaconda3/lib/python3.6/site-packages/fastai/tabular/data.py in from_df(cls, path, df, dep_var, valid_idx, procs, cat_names, cont_names, classes, **kwargs)
    111         "Create a `DataBunch` from train/valid/test dataframes."
    112         cat_names = ifnone(cat_names, [])
--> 113         cont_names = ifnone(cont_names, list(set(df)-set(cat_names)-{dep_var}))
    114         procs = listify(procs)
    115         return (TabularList.from_df(df, path=path, cat_names=cat_names, cont_names=cont_names, procs=procs)

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in __hash__(self)
   1490     def __hash__(self):
   1491         raise TypeError('{0!r} objects are mutable, thus they cannot be'
-> 1492                         ' hashed'.format(self.__class__.__name__))
   1493 
   1494     def __iter__(self):

TypeError: 'DataFrame' objects are mutable, thus they cannot be hashed
```