TextBase can now handle standard lists of classes
It was giving an error due to `list` not having the 'shape' attribute.

I added a utility function `is1d` which can be used to safely check
various types to see if they're 1d or not.

There was a 'list' being passed to this function, so I was getting 'no
attribute called 'shape''.  This fix makes that error go away for me.

Full traceback for completeness:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-9ff172a0dcfd> in <module>
----> 1 data_lm = TextLMDataBunch.from_folder(PATH, valid='test', classes=['pos', 'neg'])

~/projects/downloads/fastai/fastai/text/data.py in from_folder(cls, path, train, valid, test, classes, tokenizer, vocab, **kwargs)
    376         train_ds = (TextDataset.from_folder(path/train, classes, **txt_kwargs)
    377                     .tokenize(tokenizer, **tok_kwargs)
--> 378                     .numericalize(vocab, **num_kwargs))
    379         datasets = [train_ds, (TextDataset.from_folder(path/valid, train_ds.classes, **txt_kwargs)
    380                                .tokenize(tokenizer, **tok_kwargs)

~/projects/downloads/fastai/fastai/text/data.py in numericalize(self, vocab, max_vocab, min_freq)
    120         vocab = ifnone(vocab, Vocab.create(self.x, max_vocab, min_freq))
    121         ids = np.array([vocab.numericalize(t) for t in self.x])
--> 122         return NumericalizedDataset(vocab, ids, self.y, self.classes, encode_classes=False)
    123
    124 def _join_texts(texts:Collection[str], mark_fields:bool=True):

~/projects/downloads/fastai/fastai/text/data.py in __init__(self, vocab, ids, labels, classes, encode_classes)
     78         super().__init__(ids, labels, classes, encode_classes)
     79         self.vocab, self.vocab_size = vocab, len(vocab.itos)
---> 80         self.loss_func = F.cross_entropy if len(self.y.shape) <= 1 else F.binary_cross_entropy_with_logits
     81
     82     def get_text_item(self, idx, sep=' ', max_len:int=None):

AttributeError: 'list' object has no attribute 'shape'