Fixes issue #1311 of not being able to to run installation with pip
Removal of duplicate 'regex' package in requirements list, and ensuring
version is set to 2018.01.10, otherwise this is then incompatible with
'spacy' package.

error: regex 2018.11.22 is installed but regex==2018.01.10 is required
by {'fastai', 'spacy'}