Inference example quick_start.ipynb should use image that exists
As it currently exists, quick_start.ipnyb has an example inference step using the image

> img = PILImage.create('images/cat.jpg')

This image does not exist, and this line throws the error

> FileNotFoundError: [Errno 2] No such file or directory: 'images/cat.jpg'

This change is a minimal fix, replacing the non-existent image with one in the dataset used in this tutorial.