Fix travis-ci crash
It fixes the seg fault crash seen in travis builds.

Mostlikely the crash was caused by the exception below that appears if
the torch, cv2 and mathplotlib aren't imported in a right order.
```
ImportError: dlopen: cannot load any more object with static TLS
```
see #286 for more details.

fix typos in .travis.yml